<div class="navbar bg-base-100 bg-green-600 flex justify-center items-center">
    <div class="flex-1 flex justify-items-center justify-center">
        <a class="btn btn-ghost text-4xl text-yellow-600" style="color: #eab308;">Presupuestos de Seguros en Viviendas</a>
        <a class="btn btn-ghost text-3xl text-yellow-600" style="color: #eab308;">Boligforsikringsbudsjetter</a>
    </div>

</div>
